---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: vote
data:
  POSTGRES_HOST_AUTH_METHOD: trust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
        - name: db-data
          emptyDir: { }
      containers:
        - image: postgres:9.4
          name: db
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: POSTGRES_HOST_AUTH_METHOD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
