---
apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: result-service
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 31001
  selector:
    app: result-app