apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: vote-deployment
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
        - image: kodekloud/examplevotingapp_vote:before
          name: vote-app
